server:
  port: 8083
spring:
  application:
    name: provider
#feign:
#  hystrix:
#    enabled: true
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://master:8888/eureka/