server:
  port: 8083
spring:
  application:
    name: provider
#feign:
#  hystrix:
#    enabled: true
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1 #租期更新时间间隔
    leaseExpirationDurationInSeconds: 1 #租期到期时间
  client:
    service-url:
      defaultZone: http://master:2018/eureka/