server:
  port: 2017
spring:
  application:
    name: servercenter
eureka:
  instance:
    hostname: backup
  client:
    registerWithEureka: true # 表示是否注册自身到eureka服务器
    fetchRegistry: false # 是否从eureka上获取注册信息
    serviceUrl: #如果是多主机集群port一样，用hostname区分，如果在一台主机模拟，hostname一样用port区分
      defaultZone: http://master:2018/eureka/
  server: #关闭自我保护
    enable-self-preservation: false
#    evictionIntervalTimerInMs: 4000 #清理间隔,单位毫秒