server:
  port: 10010
spring:
  application:
    name: book
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: admin
  jpa:
    show-sql: true
    database: mysql

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1 #租期更新时间间隔
    leaseExpirationDurationInSeconds: 1 #租期到期时间
  client:
    service-url:
      defaultZone: http://master:2018/eureka/