server:
  port: 10010
spring:
  application:
    name: book
  datasource:
    driver-class-value: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: admin
  jpa:
    show-sql: true
    database: mysql

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:2018/eureka/