server:
  port: 8844
  session:
    timeout: 5

zuul:
  routes:
    provider:
      path: /v1/**
      service-id: provider
      sensitiveHeaders: "*"
    host:
      connect-timeout-millis: 6000
      socket-timeout-millis: 6000
spring:
  application:
    name: api
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
#    jdbc:mysql://juniuo.crjf2p1tdwz3.rds.cn-north-1.amazonaws.com.cn:3306/juniuo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: admin
  jpa:
    show-sql: true #运行时打印SQL语句
    database: mysql
    hibernate:
      ddl-auto: none
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 1 #租期更新时间间隔
    leaseExpirationDurationInSeconds: 1 #租期到期时间
  client:
    service-url:
      defaultZone: http://master:2018/eureka/


#    ribbon:
#      ReadTimeout: 60000
#      ConnectTimeout: 60000