server:
  port: 1111
spring:
  application:
    name: commons
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=true
#    jdbc:mysql://juniuo.crjf2p1tdwz3.rds.cn-north-1.amazonaws.com.cn:3306/juniuo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: admin
  jpa:
    show-sql: true #运行时打印SQL语句
    database: mysql
    hibernate:
      ddl-auto: none #update
#      create每次启动都会删除以前的重新创建，
eureka:
  instance:
    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://master:2018/eureka/