server:
  port: 2018
spring:
  application:
    name: servercenter
eureka:
  instance:
    hostname: master
  client:
    registerWithEureka: true # 表示是否注册自身到eureka服务器
    fetchRegistry: false # 是否从eureka上获取注册信息
    serviceUrl: #如果是多主机集群port一样，用hostname区分，如果在一台主机模拟，hostname一样用port区分
      defaultZone: http://backup:2017/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
#    evictionIntervalTimerInMs: 4000 #清理间隔,单位毫秒